CREATE TABLE [dbo].[TEL_VVOD]
(
	[ID_PARAM] INT NOT NULL PRIMARY KEY, 
    [NAME_USL] VARCHAR(175) NULL, 
    [PR_ZAP] CHAR NULL, 
    [NOM_POZ] CHAR(4) NULL, 
    [PR_VIBOR] CHAR(2) NULL, 
    [SKD1] CHAR NULL, 
    [SKD2] CHAR NULL, 
    [SKD3] CHAR NULL, 
    [NDS] CHAR NULL, 
    [PF] CHAR NULL, 
    [SUM1] REAL NULL, 
    [PR_TEL] CHAR NULL, 
    [NOM_RAZDELA] CHAR(2) NULL, 
    [PR_UDAL] CHAR NULL
)
