CREATE TABLE [dbo].[TEL_OPERATOR]
(
	[ID_OPERATOR] INT NOT NULL PRIMARY KEY, 
    [KOD_OPERATOR] CHAR(2) NULL, 
    [NAME_OPERATOR] VARCHAR(50) NULL, 
    [ID_BK] INT NULL, 
    [ID_CONNECT] INT NULL, 
    [ID_KAGENT] INT NULL, 
    [NOM_DOG] VARCHAR(22) NULL, 
    [DATE_DOG] DATE NULL
)
