CREATE TABLE [dbo].[TEL_STAC]
(
	[ID_STAC] INT NOT NULL PRIMARY KEY, 
    [ID_STAC_TEL] INT NULL, 
    [GOD] CHAR(4) NULL, 
    [MES] CHAR(2) NULL, 
    [SUM_RAZG] REAL NULL, 
    [SUM_NDS] REAL NULL, 
    [NOM_SCHET] VARCHAR(18) NULL, 
    [DATE_SCHET] DATE NULL, 
    [SUM_SKIDOK] NUMERIC(15, 2) NULL, 
    [SUM_ISKL] NUMERIC(15, 2) NULL
)
