CREATE TABLE [dbo].[TEL_MOB_RAZG]
(
	[ID_MOBVIXOD] INT NOT NULL PRIMARY KEY, 
    [ID_MOB] INT NULL, 
    [DATE_RAZG] DATE NULL, 
    [TIME_RAZG] TIME NULL, 
    [SUM_RAZG] NUMERIC(15, 2) NULL, 
    [N_TEL_OTV] VARCHAR(22) NULL, 
    [NAPR_RAZG] VARCHAR(100) NULL, 
    [NAME_RAZG] VARCHAR(100) NULL, 
    [DL_RAZG] INT NULL, 
    [NOM_STAC_TEL] CHAR(6) NULL
)
