CREATE TABLE [dbo].[TEL_MOB_USL]
(
	[ID_MOB_USL] INT NOT NULL PRIMARY KEY, 
    [ID_MOB] INT NOT NULL, 
    [SUM_RAZG] NUMERIC(15, 2) NULL, 
    [KONTRAKT] VARCHAR(20) NULL, 
    [NAME_USLUGI] VARCHAR(150) NULL, 
    [ID_PARENT] INT NULL
)
