CREATE TABLE [dbo].[TEL_MOB_USL_SPR]
(
	[ID_MOB_USL_SPR] INT NOT NULL PRIMARY KEY, 
    [NAME_USLUGI] VARCHAR(150) NULL, 
    [SUMMA_USLUGI] NUMERIC(15, 2) NULL, 
    [GOD] CHAR(4) NULL, 
    [MES] CHAR(2) NULL, 
    [PR_NDS] CHAR NULL
)
